ALTER TABLE mess_profiles
    ADD COLUMN monthly_price NUMERIC(10,2),
    ADD COLUMN description TEXT,
    ADD COLUMN food_type VARCHAR(30),
    ADD COLUMN offers_breakfast BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN offers_lunch BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN offers_dinner BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN listing_status VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
    ADD COLUMN published_at TIMESTAMP NULL,
    ADD COLUMN created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;